/* tslint:disable */
/* eslint-disable */
/**
 * Passage Management API
 * Passage\'s management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../generated/runtime';
import type { TtlDisplayUnit } from '../generated/models/TtlDisplayUnit';
import {
    TtlDisplayUnitFromJSON,
    TtlDisplayUnitFromJSONTyped,
    TtlDisplayUnitToJSON,
} from '../generated/models/TtlDisplayUnit';

/**
 *
 * @export
 * @interface UpdateMagicLinkAuthMethod
 * @deprecated this interface will be removed in version 3.0
 */
export interface UpdateMagicLinkAuthMethod {
    /**
     *
     * @type {boolean}
     * @memberof UpdateMagicLinkAuthMethod
     */
    enabled?: boolean;
    /**
     * Maximum time (IN SECONDS) for the auth to expire.
     * @type {number}
     * @memberof UpdateMagicLinkAuthMethod
     */
    ttl?: number;
    /**
     *
     * @type {TtlDisplayUnit}
     * @memberof UpdateMagicLinkAuthMethod
     * @deprecated
     */
    ttl_display_unit?: TtlDisplayUnit;
}

/**
 * Check if a given object implements the UpdateMagicLinkAuthMethod interface.
 */
export function instanceOfUpdateMagicLinkAuthMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateMagicLinkAuthMethodFromJSON(json: any): UpdateMagicLinkAuthMethod {
    return UpdateMagicLinkAuthMethodFromJSONTyped(json, false);
}

export function UpdateMagicLinkAuthMethodFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UpdateMagicLinkAuthMethod {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        enabled: !exists(json, 'enabled') ? undefined : json['enabled'],
        ttl: !exists(json, 'ttl') ? undefined : json['ttl'],
        ttl_display_unit: !exists(json, 'ttl_display_unit')
            ? undefined
            : TtlDisplayUnitFromJSON(json['ttl_display_unit']),
    };
}

export function UpdateMagicLinkAuthMethodToJSON(value?: UpdateMagicLinkAuthMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        enabled: value.enabled,
        ttl: value.ttl,
        ttl_display_unit: TtlDisplayUnitToJSON(value.ttl_display_unit),
    };
}
