name: Run Tests on PR

on:
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  APP_TOKEN: ${{ secrets.APP_TOKEN }}
  EXAMPLE_USER_ID: ${{ secrets.EXAMPLE_USER_ID }}
  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Unit Test
        run: npm run test
